version: "3.9"

services:
  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    image: vertex
    container_name: vertex
    restart: unless-stopped
    ports:
      - "8080:8080"  
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_CONNECTION: sqlite
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

