# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: vertex
#     container_name: vertex
#     restart: unless-stopped
#     tty: true
#     environment:
#       SERVICE_NAME: app
#       SERVICE_TAGS: dev
#       DB_CONNECTION: pgsql
#       DB_HOST: ep-aged-bird-a6no7ukt.us-west-2.aws.neon.tech
#       DB_PORT: 5432
#       DB_DATABASE: vertex
#       DB_USERNAME: neondb_owner
#       DB_PASSWORD: IN49KBWYHzXM
#     working_dir: /var/www
#     volumes:
#       - .:/var/www
#       - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
#     depends_on:
#       - db
#     networks:
#       - app-network

#   webserver:
#     image: nginx:alpine
#     container_name: nginx-webserver
#     restart: unless-stopped
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/var/www
#       - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - app
#     networks:
#       - app-network

#   db:
#     image: postgres:15
#     container_name: postgres
#     restart: unless-stopped
#     environment:
#       POSTGRES_DB: vertex
#       POSTGRES_USER: neondb_owner
#       POSTGRES_PASSWORD: IN49KBWYHzXM
#     ports:
#       - "5432:5432"
#     volumes:
#       - dbdata:/var/lib/postgresql/data
#     networks:
#       - app-network

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   dbdata:
#     driver: local

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vertex
    container_name: vertex
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_CONNECTION: sqlite
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

