version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vertex
    container_name: vertex
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: vertex
      DB_USERNAME: neondb_owner
      DB_PASSWORD: IN49KBWYHzXM
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./docker-compose/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - db
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "8080:80"  # Expose port 80 from Nginx internally to port 8080 externally on your host
    volumes:
      - .:/var/www  # Mount the application code to be accessible by Nginx
      - ./docker-compose/nginx/default.conf:/etc/nginx/conf.d/default.conf  # Point to your Nginx configuration file
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vertex
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: IN49KBWYHzXM
    ports:
      - "5432:5432"  # Map Postgres default port to host port 5432
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
